### PR TITLE
Added AUG-26 and updated Readme

### LINKED ISSUE #202: AUG 26 - Reordered Power Of 2
### Description

Will add solution for [AUG-26](https://leetcode.com/problems/reordered-power-of-2) Daily Challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by coderSuren**
## 🛠️ Fixes Issue

Closes #202 

## 👨‍💻 Changes proposed

Added solution for [AUG-26](https://leetcode.com/problems/reordered-power-of-2/) Challenge and updated Readme

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📷 Output Screenshots
Capture

### CODE REVIEW

**Comment by utkarsh006** [comment]
@coderSuren The code file is empty.

**Comment by coderSuren** [comment]
@utkarsh006 I Added the file now

**Comment by utkarsh006** [comment]
@coderSuren Resolve merge conflicts by today

**Comment by coderSuren** [comment]
@utkarsh006 Resolved all the Conflicts now

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
