### PR TITLE
September Readme File

### LINKED ISSUE #243: Update readme of September Challenge
### Description

can you plz assign me this issue? 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by deepshikha2708**
Closes #243  

## 👨‍💻 Changes Proposed

I have updated the readme file of september challenge and added a file for october challenge in the main readme.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📷 Output Screenshots
image

image

### CODE REVIEW

**Comment by utkarsh006** [comment]
@deepshikha2708 Add output ss not of code, also add links upto the problems of sept 30.

**Comment by utkarsh006** [comment]
@deepshikha2708 Attach the output screenshots of README.

**Comment by deepshikha2708** [comment]
done
I hope I completed the PR template :)

**Comment by utkarsh006** [comment]
@deepshikha2708 Add the oct challenge folder in the main readme.

**Comment by deepshikha2708** [comment]
ok

**Comment by utkarsh006** [comment]
LGTM ⭐

**Comment by utkarsh006** [comment]
@deepshikha2708 Raise another issue where you update SEPT challenges and write topic names for each question and update links upto sept 4 solutions only and leave other solutions link empty. That issue and PR won't be as hacktoberfest since the tasks are incomplete. Kindly, do this assigned task to avoid this PR from being disqualified.

**Comment by deepshikha2708** [comment]
but this pr is closed. I cant push it here right?

**Comment by utkarsh006** [comment]
Yes that's why I asked you to raise a new PR and issue.

**Pull request merged**
