### PR TITLE
adding oct 6 challenge

### LINKED ISSUE #240: 6th-October Leetcode Daily Challenge
### Description

6th-October Leetcode Daily Challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by kalashvasaniya**
## 🛠️ Related issue
 - 6th-October Leetcode Daily Challenge https://github.com/utkarsh006/LeetCode-Grind/issues/249

## 👨‍💻 Changes Proposed
- add daily challenge of 6th october
- add README.md

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📷 Output Screenshots
Screenshot 2022-10-12 at 9 54 34 PM

### CODE REVIEW

**Comment by utkarsh006** [comment]
@kalashvasaniya Complete the PR template(Tick all the boxes and write the issue number). Also, write approach to your code along with time and space complexities.

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya Complete the PR template(Tick all the boxes and write the issue number). Also, write approach to your code along with time and space complexities.

@utkarsh006 Now done!

**Comment by utkarsh006** [comment]
@kalashvasaniya Solution links are opening in your forked repo. Also, a tickmark has to be done like this [x]

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya Solution links are opening in your forked repo. Also, a tickmark has to be done like this [x]

@utkarsh006 Solution link now opening in main repo & tickmark issue is solved

**Comment by utkarsh006** [comment]
LGTM ⭐ Next time try to reduce the feedbacks :)

**Comment by kalashvasaniya** [comment]
> LGTM ⭐ Next time try to reduce the feedbacks :)

Sure :) Thank you!

**Pull request merged**
