### PR TITLE
Sept 28_Remove Nth Node From End of List.cpp

### PR DESCRIPTION
**Pull request by Anjali-Chaudhary3**
## 🛠️ Issue Fixed

Closes ##264

Description
This contains the solution to the daily challenge of 28th September
[Remove Nth Node From End of List]
Given the head of a linked list, remove the nth node from the end of the list and return its head.
Example:
Input: head = [1,2,3,4,5], n = 2
Output: [1,2,3,5]

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📄 Note to reviewers

Added under hacktoberfest 2022
@utkarsh006 Please review my PR

## 📷 Output Screenshots
Screenshot from 2022-10-15 13-20-59

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Anjali-Chaudhary3 Edit the README file of sept challenges.

**Comment by Anjali-Chaudhary3** [comment]
Please check it

**Comment by utkarsh006** [comment]
@Anjali-Chaudhary3 Files changed should be 2.

**Comment by Anjali-Chaudhary3** [comment]
Sir I didn't get that ,
Are you asking me update "Remove Nth Node From End of List" this file as well ?

**Comment by utkarsh006** [comment]
@Anjali-Chaudhary3 Connect over my mail : utkarshsaxena900@gmail.com

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
