### PR TITLE
JUN 17 : Binary tree cameras #77

### LINKED ISSUE #77: JUN 17 : Binary tree cameras
I will Add **JUN 17 [Binary tree cameras](https://leetcode.com/problems/binary-tree-cameras/)** and update the June Readme by adding the _Topic_ column.

### PR DESCRIPTION
**Pull request by surjyaneeh**
## 🛠️ Fixes Issue

Closes #77 

## 👨‍💻 Changes proposed
Added JUN 17 [Binary tree cameras](https://leetcode.com/problems/binary-tree-cameras/) and updated the June Readme by adding the Topic column.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by utkarsh006** [comment]
@surjyaneeh Add solution link also.

**Comment by surjyaneeh** [comment]
> @surjyaneeh Add solution link and Check spellings also.

Okay, @utkarsh006  sir.

**Comment by surjyaneeh** [comment]
> @surjyaneeh Add solution link and Check spellings also.

Okay, @utkarsh006  sir.

**Comment by utkarsh006** [comment]
Thanks for your Contribution 🎈

**Pull request merged**
