### PR TITLE
MAY 21 : Coin Change #108

### LINKED ISSUE #108: MAY 21 : Coin Change
### Description

[Problem](https://leetcode.com/problems/coin-change/) :
You are given an integer array `coins` representing coins of different denominations and an integer amount representing a total `amount` of money.

Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return `-1`.

You may assume that you have an infinite number of each kind of coin.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by surjyaneeh**
## 🛠️ Fixes Issue

Closes #108 

## 👨‍💻 Changes proposed

Added MAY 21 : Coin Change

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

image

### CODE REVIEW

**Comment by utkarsh006** [comment]
@surjyaneeh Edit the readme.

**Comment by surjyaneeh** [comment]
> @surjyaneeh Edit the readme.

@utkarsh006 sir,
If I edit the Readme now, it will link to my forked repo. Will it be okay?

**Comment by utkarsh006** [comment]
@surjyaneeh No leave it.

**Comment by utkarsh006** [comment]
Thanks for your Contribution 🎈

**Pull request merged**
