### PR TITLE
Aug 23 Daily challlenge

### PR DESCRIPTION
**Pull request by deepshikha2708**
#189 

Closes #

## 👨‍💻 Changes proposed

Added Aug 23 Leetcode challenge

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

### CODE REVIEW

**Comment by utkarsh006** [comment]
Files changed are 4. Only change the files for which this issue is created.
Follow the guidelines while writing the code.

**Comment by deepshikha2708** [comment]
the files for previous pr was added ig

**Comment by deepshikha2708** [comment]
how do i proceed now?

**Comment by utkarsh006** [comment]
Make files changed to 2.
Also follow guidelines in the code.

**Comment by deepshikha2708** [comment]
what changes do i need to make in the code?

**Comment by deepshikha2708** [comment]
i deleted the other 2 files

**Comment by utkarsh006** [comment]
@deepshikha2708 Delete this PR and make a new PR For this issue.

**Pull request closed without merging**
