### PR TITLE
July 24: Search a 2D Matrix II #43

### LINKED ISSUE #43: July 24: Search a 2D Matrix II
[Link](https://leetcode.com/problems/search-a-2d-matrix-ii/)

### PR DESCRIPTION
**Pull request by surjyaneeh**
## 🛠️ Fixes Issue

Closes #43 

## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by utkarsh006** [comment]
@surjyaneeh Edit the readme till Jul 24.

**Comment by surjyaneeh** [comment]
> @surjyaneeh Edit the readme till Jul 24.

sure.

**Comment by surjyaneeh** [comment]
> @surjyaneeh Edit the readme till Jul 24.

Is it okay now?

**Comment by utkarsh006** [comment]
@surjyaneeh Add the topic name for the questions of 16,17&18 July

**Comment by utkarsh006** [comment]
Thanks for your Contribution 🎈

**Pull request merged**
