### PR TITLE
Added 15-Oct leetcode daily challenge

### LINKED ISSUE #260: 15-October LeetCode Daily Challenge
### **Delete the Middle Node of a Linked List**
You are given the head of a linked list. Delete the middle node, and return the head of the modified linked list.
Example :

Input: head = [1,2,3,4]
Output: [1,2,4]
Explanation:
The figure represents the given linked list.
For n = 4, node 2 with value 3 is the middle node, which is marked in red.

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by Dharansh-Neema**
Closes 
#260 

## 👨‍💻 Changes Proposed
Solved 15-OCT daily challenge and updated readme file in new branch -> LeetCode-Daily.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📷 Output Screenshots
image

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Dharansh-Neema Follow the guidelines in code section. Also attach how your readme output is looking.

**Comment by Dharansh-Neema** [comment]
@utkarsh006 Can you please specify which guidelines is not followed from [Contribution Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md).

Here is the Screen shot of **README** file.  

image

**Comment by utkarsh006** [comment]
@Dharansh-Neema Guess you haven't read the guidelines well else you have understood that what mistakes you have done while writing the code.

**Comment by Dharansh-Neema** [comment]
@utkarsh006 I guess I missed the Explanation part of the problem, which is now been added. Anything else left out please let me know. Thanks

**Comment by utkarsh006** [comment]
@Dharansh-Neema Yes you were correct. Now, Resolve merge conflicts.

**Comment by Dharansh-Neema** [comment]
@utkarsh006 I think it's done now.

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
