### PR TITLE
Create AUG 7_Vomel.py

### LINKED ISSUE #140: August 7:Daily Leetcode challenge
### Description

1220. Count Vowels Permutation
Hard

2078

143

Add to List

Share
Given an integer n, your task is to count how many strings of length n can be formed under the following rules:

Each character is a lower case vowel ('a', 'e', 'i', 'o', 'u')
Each vowel 'a' may only be followed by an 'e'.
Each vowel 'e' may only be followed by an 'a' or an 'i'.
Each vowel 'i' may not be followed by another 'i'.
Each vowel 'o' may only be followed by an 'i' or a 'u'.
Each vowel 'u' may only be followed by an 'a'.
Since the answer may be too large, return it modulo 10^9 + 7.

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by deepshikha2708**
## 🛠️ Fixes 140

Closes #140 
## 👨‍💻 Changes proposed

added code for august 7 daily challenge

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📷 Output Screenshots
image

### CODE REVIEW

**Comment by utkarsh006** [comment]
@deepshikha2708 Follow the guidelines. Code should be in C++

**Comment by deepshikha2708** [comment]
ok i will convert it

**Comment by utkarsh006** [comment]
@deepshikha2708 Read the guidelines properly and make the changes.

**Comment by deepshikha2708** [comment]
please review it and tell me if any changes is required.

**Comment by utkarsh006** [comment]
@deepshikha2708 Resolve the merge conflicts.

**Comment by deepshikha2708** [comment]
I am not able to understand the issue in the readme

**Comment by utkarsh006** [comment]
@deepshikha2708 Kindly Complete the PR by today!

**Comment by deepshikha2708** [comment]
image

its coming something like this, please help me with it

**Comment by utkarsh006** [comment]
@deepshikha2708 Contact me over the general section in the discord channel

**Pull request closed without merging**
