### PR TITLE
Sept 25_Design Circular Queue.cpp

### PR DESCRIPTION
**Pull request by Anjali-Chaudhary3**
ISSUE NO:#263 
**DESCRIPTION**

**Design Circular Queue**
Implement the MyCircularQueue class to perform the following operations on the circular queue
1.add element 
2.delete element
3.check if the queue is empty
4.check if the queue is full

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📄 Note to reviewers

Added under Hacktoberfest 2022
@utkarsh006  Please review my PR 

## 📷 Output Screenshots
Screenshot from 2022-10-15 12-22-32

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Anjali-Chaudhary3  Create an issue. If you continue this behavior, will mark your PR as spam.

**Comment by Anjali-Chaudhary3** [comment]
i am sorry sir,i am doing contribution for first time. I have made the
changes

**Comment by utkarsh006** [comment]
@Anjali-Chaudhary3 Its fine I can understand. Do mention issue number in your PR.

**Comment by Anjali-Chaudhary3** [comment]
Done

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
