### PR TITLE
JUL 16 : Out of Boundary Paths #115

### LINKED ISSUE #115: JUL 16 : Out of Boundary Paths
### Description

1. Add JUL 16 [Out of Boundary Paths](https://leetcode.com/problems/out-of-boundary-paths/) problem
2. Add the solution column and Link to the solutions.

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by surjyaneeh**
## 🛠️ Fixes Issue

Closes #115 

## 👨‍💻 Changes proposed

Added JUL 16 [Out of Boundary Paths](https://leetcode.com/problems/out-of-boundary-paths/) problem
Added the solution column and Link to the solutions.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

image

### CODE REVIEW

**Comment by surjyaneeh** [comment]
> @surjyaneeh Make the proper use of curly braces in the second approach. Also, use them from the next line.

Okay, I will do the necessary changes.

**Comment by utkarsh006** [comment]
@surjyaneeh After the brute force, explain memoization too. Don't jump directly to the tabulation part.

**Comment by surjyaneeh** [comment]
> @surjyaneeh After the brute force, explain memoization too. Don't jump directly to the tabulation part.

Sure sir,  need some more time.

**Comment by surjyaneeh** [comment]
> @surjyaneeh After the brute force, explain memoization too. Don't jump directly to the tabulation part.

I have added all four approaches along with their complexities, kindly let me know if there is anything else to be modified.

**Comment by utkarsh006** [comment]
Thanks for your Contribution 🎈

**Pull request merged**
