### PR TITLE
July 21 updated

### LINKED ISSUE #29: July 21: Reverse Linked List II
Given the head of a singly linked list and two integers left and right where left <= right, reverse the nodes of the list from position left to position right, and return the reversed list.

### PR DESCRIPTION
**Pull request by Soumya-Kushwaha**
Fixed #29

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Soumya-Kushwaha Explain the approach along with Time and space complexity.

**Comment by utkarsh006** [comment]
@Soumya-Kushwaha Kindly do the changes by midnight else your pr will be closed!

**Comment by Soumya-Kushwaha** [comment]
@utkarsh006 updated

**Comment by utkarsh006** [comment]
@Soumya-Kushwaha You have not done the tasks I have told you to do !

**Pull request closed without merging**
