### PR TITLE
Added January Readme file

### LINKED ISSUE #90: Add readme file of january
### Description

Will add the january readme file

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by tanya-gupta25**
## 🛠️ Fixes Issue

Closes #90

## 👨‍💻 Changes proposed
Added January Readme file

## Screenshots
image
image

### CODE REVIEW

**Comment by utkarsh006** [comment]
@tanya-gupta25 Complete the PR Template fully.

**Comment by tanya-gupta25** [comment]
> @tanya-gupta25 Complete the PR Template fully.

From where I should take the template, it's gone for this one

**Comment by utkarsh006** [comment]
@tanya-gupta25 Attach the screenshot of how your changes are looking.

**Comment by tanya-gupta25** [comment]
> @tanya-gupta25 Attach the screenshot of how your changes are looking.

@utkarsh006 Done

**Comment by utkarsh006** [comment]
@tanya-gupta25 I want to see the output. Also add solution column to the readme.

**Comment by utkarsh006** [comment]
@tanya-gupta25 Level1 due to not following guidelines and not attaching proper output screenshots.

**Comment by tanya-gupta25** [comment]
I was updating it naa, I did some mistakes

**Comment by utkarsh006** [comment]
You must have focussed and then comment for a review. Good luck next time. Thanks for your Contribution 🎈

**Pull request merged**
