### PR TITLE
Update README.md & adding a problem in Sept folder

### LINKED ISSUE #234: Add a problem and update README.md
### What happened?

image

### How can we reproduce this bug?

can I add the september challenge here and thereby add one daily leetcode challenge for september?

### PR DESCRIPTION
**Pull request by deepshikha2708**
Closes  #234 

## 👨‍💻 Changes Proposed

Updated the Readme File and added September 4 Leetcode Daily Challenge 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have star this repo.

## 📷 Output Screenshots

image

### CODE REVIEW

**Comment by utkarsh006** [comment]
@deepshikha2708 Contribute a problem with your PR and complete the PR template.

**Comment by deepshikha2708** [comment]
ok

**Comment by deepshikha2708** [comment]
done

**Comment by utkarsh006** [comment]
@deepshikha2708 Question that you have solved is not of the Leetcode Sept Challenges. Do read the guidelines well and try to not be in a hurry of merging PR's.

**Comment by utkarsh006** [comment]
@deepshikha2708 Use braces from the next line and write the approach in points  using (-). Also, complete the PR template.

**Comment by deepshikha2708** [comment]
how do I complete the PR template?

**Comment by utkarsh006** [comment]
@deepshikha2708 Connect over the mail.

**Comment by utkarsh006** [comment]
LGTM ⭐

**Pull request merged**
