### PR TITLE
Adding APR20 Challenge Solution

### LINKED ISSUE #88: Add APR 20 - Binary Search Tree Iterator Solution
### Description

Will add APR 20 Challenge Solution and update link in the readme.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by Rakesh9100**
## 🛠️ Fixes Issue

Closes #88 

## 👨‍💻 Changes proposed
Added APR 20 - Binary Search Tree Iterator Solution.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Rakesh9100 Read the contributing guidelines.

**Comment by utkarsh006** [comment]
@Rakesh9100 Complete the PR Template

**Comment by Rakesh9100** [comment]
> @Rakesh9100 Complete the PR Template

Done Kindly check.

**Comment by utkarsh006** [comment]
@Rakesh9100 Add approaches to the code and edit the readme correctly.

**Comment by Rakesh9100** [comment]
ADDED 2 APPROACHES. And I can't update the readme since we can update the link after the project is merged into your repo so see to it.

**Comment by utkarsh006** [comment]
Thanks for your Contribution 🎈

**Pull request merged**
