### PR TITLE
Adding APR27 Challenge Solution

### LINKED ISSUE #117: APR27 - Smallest String With Swaps Challenge Solution
### Description

I would add APR27 Challenge "Smallest String With Swaps" Solution.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

### PR DESCRIPTION
**Pull request by Rakesh9100**
## 🛠️ Fixes Issue

Closes #117 

## 👨‍💻 Changes proposed
I have added APR27 - Smallest String With Swaps Challenge Solution.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Added Two Approaches.

### CODE REVIEW

**Comment by utkarsh006** [comment]
@Rakesh9100 Go through the contributing guidelines and make the necessary changes.

**Comment by utkarsh006** [comment]
@Rakesh9100 Use the curly braces from the next line. Explain approach2 well and take variables name in that approach meaningful.

**Comment by Rakesh9100** [comment]
OK

**Comment by utkarsh006** [comment]
You are not following the guidelines buddy. Kindly do changes to your PR till midnight else your PR will be closed.

**Comment by Rakesh9100** [comment]
> You are not following the guidelines buddy. Kindly do changes to your PR till midnight else your PR will be closed.

Whats the issue now since I game Complexities and wrote the Approach Methods name and also changed the screenshots. If any thing left then kindly tell since I did everything according to contributing guidelines.

**Comment by Rakesh9100** [comment]
Kindly check PR now @utkarsh006

**Comment by utkarsh006** [comment]
Thanks for your Contribution 🎈 Level 1 due to more no. of reviews by the Project Admin.

**Comment by Rakesh9100** [comment]
> Thanks for your Contribution 🎈 Level 1 due to more no. of reviews by the Project Admin.

Okay no issues. Will follow the CGs now.

**Pull request merged**
